# Generated by Django 4.2.11 on 2025-07-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Habitus Palette', max_length=100)),
                ('colors', models.TextField(help_text='Semicolon-separated hex colors like #FFFFFF;#1A1A1A;...')),
            ],
        ),
        migrations.CreateModel(
            name='VectorizedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original_images/')),
                ('vectorized_image', models.ImageField(upload_to='vector_output/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
