# Generated by Django 4.2.11 on 2025-07-24 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vectorizer_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorizationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original_images/')),
                ('vectorized_image', models.ImageField(upload_to='vector_output/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('palette_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vectorizer_tool.colorpalette')),
            ],
        ),
        migrations.DeleteModel(
            name='VectorizedImage',
        ),
    ]
