# Generated by Django 4.2.11 on 2025-07-30 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vectorizer_tool', '0003_vectorizationjob_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBNOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_pdf', models.FileField(blank=True, null=True, upload_to='pbn_outputs/pdfs/')),
                ('output_jpeg', models.FileField(blank=True, null=True, upload_to='pbn_outputs/jpegs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
