# Generated by Django 4.2.11 on 2025-07-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorizer_tool', '0004_pbnoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbnoutput',
            name='output_svg',
            field=models.FileField(blank=True, null=True, upload_to='pbn_outputs/svgs/'),
        ),
        migrations.AlterField(
            model_name='pbnoutput',
            name='output_jpeg',
            field=models.ImageField(blank=True, null=True, upload_to='pbn_outputs/jpegs/'),
        ),
    ]
