# Generated by Django 4.2.11 on 2025-07-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorizer_tool', '0005_pbnoutput_output_svg_alter_pbnoutput_output_jpeg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbnoutput',
            name='output_jpeg',
        ),
        migrations.AddField(
            model_name='pbnoutput',
            name='resized_jpeg',
            field=models.ImageField(blank=True, null=True, upload_to='outputs/resized_jpeg/'),
        ),
    ]
